# Example confifuration for the Event exporter daemon
---
events:
  # Exports all events to the `matrix` notifier
  - reason: [Started, Completed]
    to: [matrix]
  - type: [Warning]
    to: [matrix]

notifiers:
  - name: matrix
    template: |
      {% if type == "Normal" %}ℹ{% else %}⚠️{% endif %} A **{{ reason }}** event occured at **{{ eventTime }}**:<br/>
      > {{ message }}

      This relates to the **{{ involvedObject.apiVersion }}:{{ involvedObject.kind }}** `{{ involvedObject.name }}` in the `{{ involvedObject.namespace }}` namespace.

      ---
    spec:
      kind: Matrix
      homeserverUrl: https://matrix.org
      userId: "@tootparis-bot:matrix.org"
      passwordEnv: MATRIX_PASSWORD
      roomId: "!ckZCbuPXdzdLOgdQsq:matrix.org"
