{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubeventsd.fullname" . }}
  labels:
    {{- include "kubeventsd.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "watch", "list"]
{{- end -}}
