apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubeventsd.fullname" . }}-config
  labels:
    {{- include "kubeventsd.labels" . | nindent 4 }}
data:
  config.yaml: |-
{{ toYaml .Values.kubeventsd.config | indent 4 }}
