apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeventsd.fullname" . }}
  labels:
    {{- include "kubeventsd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.updateStrategy }}
  strategy: {{- toYaml .Values.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubeventsd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kubeventsd.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kubeventsd.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "kubeventsd.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: config-volume
              mountPath: /config
          env:
            - name: KUBEVENTSD_CONFIG_PATH
              value: /config/config.yaml
            - name: RUST_LOG
              value: {{ .Values.kubeventsd.logs }}
          envFrom:
            - secretRef:
                name: {{ include "kubeventsd.secretName" . }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "kubeventsd.fullname" . }}-config
