{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeventsd.secretName" . }}
  labels:
    {{- include "kubeventsd.labels" . | nindent 4 }}
type: Opaque
data: {{ if not .Values.secret.data }}{}{{ end }}
{{- range $k, $v := .Values.secret.data }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- end }}
